version: '3.8'

services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: feltexdb
    networks:
      - feltex-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev01:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.5
    networks:
      - feltex-network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

networks:
  feltex-network: {}



volumes:
  postgres_dev01:
